/*  Capture data returned by CashNet, using structure defined by that system
*/
create table cashnet_log (
  ucla_ref_no varchar2(40) not null --the reference ID we create
, result_code varchar2(3) not null  --result value returned by CashNet
, cn_trans_no varchar2(10) not null --Success/failure transaction ID generated by CashNet
, cn_batch_no varchar2(5) not null  --Batch number generated by CashNet
, pmt_code varchar2(6) not null     --Payment type in CashNet; CC=credit card; ACHWEB=echeck
, eff_date date not null            --Effective date in CashNet of transaction
, cn_details varchar2(1000)         --Catch-all for other CashNet fields we may want to review; can be null
, constraint cashnet_log_pk primary key (cn_trans_no)
)
;
-- Extra index for queries
create index cashnet_log_ucla_ref_no_ix on cashnet_log (ucla_ref_no);
